version: '3.8'
services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: bolt://localhost:7687 
    networks:
      - appNetwork

  frontend:
    depends_on: 
     - backend
    build:
     context: ./web
    networks:
      - appNetwork
networks:
  appNetwork:
    driver: bridge
